### PR TITLE
Add current directory to `apistar new --layout minimal`

### PR DESCRIPTION
**Pull request by RadoRado**
Otherwise getting:

```
$ apistar new --layout minimal
Usage: apistar new [OPTIONS] TARGET_DIR

Error: Missing argument "target_dir".
```

### CODE REVIEW

**Comment by tomchristie** [comment]
Yup. Tho let's put the '.' before the '--layout minimal' so it's harder to miss in a cut and paste.

We did used to default to the CWD. We might want to add that behaviour back in?

**Comment by RadoRado** [comment]
@tomchristie You mean something like:

```
$ apistar new $(pwd) --layout minimal
```

**Comment by tomchristie** [comment]
Yes, but just '.' rather than '$(pwd)'

**Comment by tomchristie** [comment]
Having the dot at the very end of the command line means some users might not see it and manage to miss it from a copy n paste (that's my experience from the Django REST framework docs anyhows)

**Comment by RadoRado** [comment]
@tomchristie :+1:

**Pull request merged**
