### PR TITLE
Fix for Python defaulting to using stdlib typing

### PR DESCRIPTION
**Pull request by FFX01**
Fixes issue #122.

Solution taken from #306

### CODE REVIEW

**Comment by tomchristie** [comment]
Not keen on `if False` here. Could we use `typing.Type` string literals for the `Type` annotation instead, maybe?

**Comment by FFX01** [comment]
@tomchristie 

I'll try it out and see if it works.

**Comment by FFX01** [comment]
@tomchristie 

Unfortunately, using a string literal here doesn't seem to work.

The issue is that when `from typing import ...` is called on my system it is defaulting to the stdlib `typing` module which does not include a declaration for `Type`. This is happening inside of the virtualenv because I believe module imports are first searched under the standard library and then `site-packages`.

So, I'm trying to figure out a fix that doesn't involve adding a new path to the global `$PYTHONPATH` env variable.

**Comment by FFX01** [comment]
This is only an issue under Python 3.5. However, Python 3.5 is the standard version on most *buntu systems, so I think this is a major issue.

**Pull request closed without merging**
