### PR TITLE
Django ORM Support

### PR DESCRIPTION
**Pull request by nirgn975**
Issue: #75
Continuation of the work in #153 
My Twitter profile: [nirgn975](https://twitter.com/nirgn975)

### CODE REVIEW

**Comment by nirgn975** [comment]
@tomchristie Will add tests for it in a separate PR

**Comment by tomchristie** [comment]
Looking rad!! Will catch up w/ you on it tomorrow.

**Comment by tomchristie** [comment]
💖 🌟 💜 ⚡️ 💝

Totally roarsome!!!

**Comment by nirgn975** [comment]
@tomchristie Ready to be merged :smile:

**Comment by nirgn975** [comment]
@tomchristie We are green again

**Comment by tomchristie** [comment]
Rrrrraaaaawwwwwrrrrrr!!!!!!

**Comment by linuxlewis** [comment]
:+1: Awesome

**Pull request merged**
