### PR TITLE
Type-annotate apistar.exceptions

### PR DESCRIPTION
**Pull request by weargoggles**

### CODE REVIEW

**Comment by tomchristie** [comment]
👍  Ta!

**Comment by tomchristie** [comment]
Okay I'm clear not paying enough attention, actually the messages can be dicts too. Not obv. why mypy hasn't picked up on that.

**Comment by tomchristie** [comment]
Changing the name to `detail` now, as I think that's marginally less deceptive (ie. exception details can also be data structures)

**Comment by weargoggles** [comment]
Needs to be run with --check-untyped-defs to check calls to already typed functions inside those not yet typed.

**Comment by tomchristie** [comment]
Good call! Looking into the output of that now!

**Comment by tomchristie** [comment]
Ran into some roadblocks trying to switch that flag on, so I've punted on it for now.

**Pull request merged**
