### PR TITLE
Add support for converting to coreschema types.

### PR DESCRIPTION
**Pull request by jriggins**
Currently Boolean, Integer, and Number types

### CODE REVIEW

**Comment by jriggins** [comment]
image

image

image

**Comment by tomchristie** [comment]
💥

**Comment by adawolfs** [comment]
What is the main purpose of this? I'm looking for a way to implement [**this**](https://github.com/tomchristie/apistar/issues/211) and I've found that it's caused because the defined types are replaced by coreapi types

**Comment by tomchristie** [comment]
This ensures that we have rich type descriptions in the schema, and can render appropriate types of controls. Later we can include descriptions too, which we're not yet doing.

**Pull request merged**
