### PR TITLE
API Docs

### PR DESCRIPTION
**Pull request by tomchristie**
Refs #71.

Well, it's a start...

```
def docs(schema: APISchema, templates: Templates):
    index = templates.get_template('apistar/index.html')
    langs = ['python', 'javascript', 'shell']
    def static(path):
        return '/static/' + path
    return index.render(document=schema, static=static, langs=langs)
```

image

### CODE REVIEW

**Comment by audiolion** [comment]
Where are all the references to `{% load rest_framework %}` coming from?

This looks awesome to me!

**Comment by tomchristie** [comment]
Still some bits to be removed yup. Porting across from REST framework (except ultimately it'll work better with apistar, given the schema design)

**Comment by maziarz** [comment]
This is awesome!

**Comment by tomchristie** [comment]
screen shot 2017-05-08 at 13 01 11

*-Lookin sharp-*

**Comment by auvipy** [comment]
amazing work :1st_place_medal:

**Comment by tomchristie** [comment]
Okay, let's merge this in, in it's current state.
A little more to do here, but no reason not to treat those bits as a separate PR at this point.

**Pull request merged**
