### PR TITLE
Use all the Django settings

### PR DESCRIPTION
**Pull request by globophobe**
I needed to change the AUTH_USER_MODEL setting. Maybe it's useful to use all the Django settings.

### CODE REVIEW

**Comment by ssteinerx** [comment]
Low impact, code-wise, but I'm writing a Django API Star ✨🚀✨🌟  demo app, and needed this, too.

**Comment by tomchristie** [comment]
Good call, yes.
I've got a better picture now of how API Star will fit into Django land, so expect some adaptation in the future, but this is a worthwhile change for now.
Thanks!

  😄

**Comment by tomchristie** [comment]
I'm gonna roll this back for 0.2, and just explicitly include `AUTH_USER_MODEL`.
We should limit the settings to anything that Django core actually uses to affect models.

**Comment by globophobe** [comment]
I'm looking forward to what you've got in the pipeline for Django.

**Comment by tomchristie** [comment]
0.2 does the groundwork of allowing us to support multiple different frameworks, tho currently that extends to asyncio and wsgi options.

Full "run inside Django" and "run inside Flask" options are (ideally?) planned for a later release.

The Django ORM support *is* better in 0.2 tho, since we can now support context managed components, allowing us to introduce a `Session` that handles `commit`/`rollback` behaviors, and properly cleans up connections.

**Pull request merged**
